name: Build distribution

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

env:
  SHELL: /bin/bash

jobs:
  buildNative:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:multilib-devel
    steps:
      - name: Install packages
        run: pacman --noconfirm -Sy sbt jdk-openjdk git mingw-w64 clang nasm
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Fix dubious permissions error
        run: git config --global --add safe.directory /__w/MPPatch/MPPatch
      - name: Fetch git tags.
        run: git fetch --prune --unshallow --tags
      - name: Build native binaries
        run: scripts/build_linux_natives.sh
      - uses: actions/upload-artifact@v2
        with:
          name: mppatch_linux_natives.tar.gz
          path: mppatch_linux_natives.tar.gz

  buildInstallerLinux:
    runs-on: ubuntu-latest
    needs:
      - buildNative
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Fetch git tags.
        run: git fetch --prune --unshallow --tags
      - uses: actions/download-artifact@v2
        with:
          name: mppatch_linux_natives.tar.gz
          path: mppatch_linux_natives.tar.gz
      - name: Build Linux installer
        run: scripts/build_linux_installer.sh
      - uses: actions/upload-artifact@v2
        with:
          name: mppatch_linux_installer.tar.gz
          path: mppatch_linux_installer.tar.gz
